// Script.WebEx.js
(function(){function executeScript(){
Type.registerNamespace('SystemEx.Html');SystemEx.Html.CloseEventArgs=function(){}
SystemEx.Html.CloseEventArgs.prototype={get_wasClean:function(){return this.wasClean;},initCloseEvent:function(typeArg,canBubbleArg,cancelableArg,wasCleanArg){this.initCloseEvent(typeArg, canBubbleArg, cancelableArg, wasCleanArg);}}
SystemEx.Html.MessageEventArgs=function(){}
SystemEx.Html.MessageEventArgs.prototype={get_data:function(){return this.data;}}
SystemEx.Html.WebSocket=function(){}
SystemEx.Html.WebSocket.create=function(url,protocol){return ((protocol==null)?new WebSocket(url):new WebSocket(url, protocol));}
SystemEx.Html.WebSocket.prototype={get_url:function(){return this.url;},get_readyState:function(){return this.readyState;},get_bufferedAmount:function(){return this.bufferedAmount;},get_onOpen:function(){return this.onopen;},set_onOpen:function(value){this.onopen = value;return value;},get_onMessage:function(){return this.onmessage;},set_onMessage:function(value){this.onmessage = value;return value;},get_onError:function(){return this.onerror;},set_onError:function(value){this.onerror = value;return value;},get_onClose:function(){return this.onclose;},set_onClose:function(value){this.onclose = value;return value;},get_protocol:function(){return this.protocol;},send:function(data){return this.send(data);},close:function(){this.close();}}
SystemEx.Html.LocalStorage=function(){}
SystemEx.Html.LocalStorage.getItem=function(key){try{return window.localStorage.getItem(key);}catch($0){throw new Error('IOException:'+$0);}}
SystemEx.Html.LocalStorage.key=function(index){try{return window.localStorage.key(index);}catch($0){throw new Error('IOException:'+$0);}}
SystemEx.Html.LocalStorage.get_length=function(){try{return window.localStorage.length;}catch($0){throw new Error('IOException:'+$0);}}
SystemEx.Html.LocalStorage.removeItem=function(key){try{window.localStorage.removeItem(key);}catch($0){throw new Error('IOException:'+$0);}}
SystemEx.Html.LocalStorage.setItem=function(key,value){try{window.localStorage.setItem(key, value);}catch($0){throw new Error('IOException:'+$0);}}
Type.registerNamespace('SystemEx');SystemEx.JSArrayEx=function(){}
SystemEx.JSArrayEx.clear=function(array,index,length){}
SystemEx.JSArrayEx.copy=function(source,sourceIndex,destination,destinationIndex,length){if((source==null)||(destination==null)){throw new Error('NullPointerException:');}var $0=source.length;var $1=destination.length;if((sourceIndex<0)||(destinationIndex<0)||(length<0)||(sourceIndex+length>$0)||(destinationIndex+length>$1)){throw new Error('IndexOutOfBoundsException:');}SystemEx.JSArrayEx.$0(source,sourceIndex,destination,destinationIndex,length);}
SystemEx.JSArrayEx.$0=function($p0,$p1,$p2,$p3,$p4){if(($p0===$p2)&&($p1<$p3)){$p1+=$p4;for(var $0=$p3+$p4;$0-->$p3;){$p2[$0]=$p0[--$p1];}}else{for(var $1=$p3+$p4;$p3<$1;){$p2[$p3++]=$p0[$p1++];}}}
SystemEx.JSConvertEx=function(){}
SystemEx.JSConvertEx.singleToInt32Bits=function(v){SystemEx.JSConvertEx.$2[0]=v;return SystemEx.JSConvertEx.$1[0];}
SystemEx.JSConvertEx.int32BitsToSingle=function(v){SystemEx.JSConvertEx.$1[0]=v;return SystemEx.JSConvertEx.$2[0];}
SystemEx.JSConvertEx.bytesToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]);}return $0;}
SystemEx.JSConvertEx.uBytesToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]&255);}return $0;}
SystemEx.JSConvertEx.singlesToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]);}return $0;}
SystemEx.JSConvertEx.doublesToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]);}return $0;}
SystemEx.JSConvertEx.ints16ToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]);}return $0;}
SystemEx.JSConvertEx.uInt16ToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]&65535);}return $0;}
SystemEx.JSConvertEx.ints32ToJSArray=function(data){var $0=[];var $1=data.length;for(var $2=$1-1;$2>=0;$2--){$0.set($2,data[$2]);}return $0;}
SystemEx.StringBuilderEx=function(){}
SystemEx.StringBuilderEx.getLength=function(b){return b.length;}
Type.registerNamespace('SystemEx.IO');SystemEx.IO.FileAccess=function(){};SystemEx.IO.FileAccess.prototype = {read:1,readWrite:3,write:2}
SystemEx.IO.FileAccess.registerEnum('SystemEx.IO.FileAccess',false);SystemEx.IO.FileMode=function(){};SystemEx.IO.FileMode.prototype = {append:6,create:2,createNew:1,open:3,openOrCreate:4,truncate:5}
SystemEx.IO.FileMode.registerEnum('SystemEx.IO.FileMode',false);SystemEx.IO.MemoryStream=function(buffer){SystemEx.IO.MemoryStream.initializeBase(this);this.$1=((buffer==null)?SystemEx.IO.MemoryStream.makeBuffer(16):buffer);}
SystemEx.IO.MemoryStream.makeBuffer=function(initialSize){return new Array((initialSize!==0)?initialSize:16);}
SystemEx.IO.MemoryStream.prototype={$0:0,$1:null,$2:0,get_buffer:function(){return this.$1;},toArray:function(){var $0=new Array(this.$0);SystemEx.JSArrayEx.copy(this.$1,0,$0,0,this.$0);return $0;},get_length:function(){return this.$0;},get_position:function(){return this.$2;},readByte:function(){return ((this.$2<this.$1.length)?this.$1[this.$2++]:-1);},writeByte:function(b){if(this.$1.length===this.$0){var $0=new Array(this.$1.length*3/2);SystemEx.JSArrayEx.copy(this.$1,0,$0,0,this.$0);this.$1=$0;}this.$1[this.$0++]=b;},close:function(){this.$1=null;}}
SystemEx.IO.SE=function(){}
SystemEx.IO.SE.internalReadByte=function(s){var $0=s.readByte();if($0===-1){throw new Error('IOException: EOF');}return $0;}
SystemEx.IO.SE.$0=function($p0){var $0=$p0.readByte();var $1=SystemEx.IO.SE.internalReadByte($p0);return (($0<<8)|$1);}
SystemEx.IO.SE.readByte=function(s){var $0=s.readByte();if($0===-1){throw new Error('IOException: EOF');}return $0;}
SystemEx.IO.SE.readBytes=function(s,b,offset,length){if((offset===0)&&(length===0)){length=b.length;}while(length>0){var $0=s.read(b,offset,length);if($0<=0){throw new Error('IOException: EOF');}offset+=$0;length-=$0;}}
SystemEx.IO.SE.readBoolean=function(s){return (SystemEx.IO.SE.readByte(s)!==0);}
SystemEx.IO.SE.readChar=function(s){var $0=s.readByte();var $1=SystemEx.IO.SE.internalReadByte(s);return (($0<<8)|$1);}
SystemEx.IO.SE.readInt16=function(s){var $0=s.readByte();var $1=SystemEx.IO.SE.internalReadByte(s);return (($0<<8)|$1);}
SystemEx.IO.SE.readInt32=function(s){var $0=s.readByte();var $1=s.readByte();var $2=s.readByte();var $3=SystemEx.IO.SE.internalReadByte(s);return ($0<<24)|($1<<16)|($2<<8)|$3;}
SystemEx.IO.SE.readInt64=function(s){var $0=SystemEx.IO.SE.readInt32(s);var $1=SystemEx.IO.SE.readInt32(s)&4294967295;return ($0<<32)|$1;}
SystemEx.IO.SE.readSingle=function(s){return SystemEx.JSConvertEx.int32BitsToSingle(SystemEx.IO.SE.readInt32(s));}
SystemEx.IO.SE.readDouble=function(s){throw new Error('NotSupportedException: readDouble');}
SystemEx.IO.SE.readString=function(s){var $0=SystemEx.IO.SE.$0(s);var $1=new ss.StringBuilder();while($0>0){$0-=SystemEx.IO.SE.$1(s,$1);}return $1.toString();}
SystemEx.IO.SE.readStringLine=function(s){throw new Error('NotSupportedException: ReadLine');}
SystemEx.IO.SE.$1=function($p0,$p1){var $0=SystemEx.IO.SE.internalReadByte($p0);if(($0&128)===0){$p1.append($0);return 1;}if(($0&224)===176){var $1=SystemEx.IO.SE.internalReadByte($p0);$p1.append(((($0&31)<<6)|($1&63)));return 2;}if(($0&240)===224){var $2=$p0.readByte();var $3=SystemEx.IO.SE.internalReadByte($p0);$p1.append(((($0&15)<<12)|(($2&63)<<6)|($3&63)));return 3;}throw new Error('IOException: UTFDataFormat:');}
SystemEx.IO.SE.writeByte=function(s,v){s.writeByte(v);}
SystemEx.IO.SE.writeBytes=function(s,v){var $0=v.length;for(var $1=0;$1<$0;$1++){s.writeByte(v.charAt($1)&255);}}
SystemEx.IO.SE.writeBoolean=function(s,v){s.writeByte((v)?1:0);}
SystemEx.IO.SE.writeChar=function(s,v){s.writeByte(v>>8);s.writeByte(v);}
SystemEx.IO.SE.writeInt16=function(s,v){s.writeByte(v>>8);s.writeByte(v);}
SystemEx.IO.SE.writeInt32=function(s,v){s.writeByte(v>>24);s.writeByte(v>>16);s.writeByte(v>>8);s.writeByte(v);}
SystemEx.IO.SE.writeInt64=function(s,v){SystemEx.IO.SE.writeInt32(s,(v>>32));SystemEx.IO.SE.writeInt32(s,v);}
SystemEx.IO.SE.writeSingle=function(s,v){SystemEx.IO.SE.writeInt32(s,SystemEx.JSConvertEx.singleToInt32Bits(v));}
SystemEx.IO.SE.writeDouble=function(s,v){throw new Error('NotSupportedException: writeDouble');}
SystemEx.IO.SE.writeString=function(s,v){var $0=new SystemEx.IO.MemoryStream();for(var $1=0;$1<v.length;$1++){var $2=v.charAt($1);if(($2>0)&&($2<80)){$0.writeByte($2);}else if($2<'\u0800'){$0.writeByte(192|(31&($2>>6)));$0.writeByte(128|(63&$2));}else{$0.writeByte(224|(15&($2>>12)));$0.writeByte(128|(63&($2>>6)));$0.writeByte(128|(63&$2));}}SystemEx.IO.SE.writeInt16(s,$0.get_length());s.write($0.get_buffer(),0,$0.get_length());}
SystemEx.IO.FileInfo=function(fileName,parent){while(fileName.endsWith('/')&&(fileName.length>0)){fileName=fileName.substring(0,fileName.length-1);}var $0=fileName.lastIndexOf('/');if($0===-1){this.$1=fileName;}else if($0===0){this.$1=fileName.substring($0,fileName.length);this.$0=((this.$1==='')?null:SystemEx.IO.FileInfo.root);}else{this.$1=fileName.substring($0+1,fileName.length);this.$0=new SystemEx.IO.FileInfo(fileName.substring(0,$0));}}
SystemEx.IO.FileInfo.prototype={$0:null,$1:null,get_name:function(){return this.$1;},get_$2:function(){return ((this.$0==null)?'':this.$0.get_path());},get_$3:function(){return this.$0;},get_path:function(){return ((this.$0==null)?this.$1:this.$0.get_path()+'/'+this.$1);},$4:function(){return ((this.$1==='')&&(this.$0==null));},$5:function(){if(this.$4()){return true;}if(this.$0==null){return false;}return this.$0.$5();},$6:function(){var $0=this.$7().get_path();return (($0.length===0)?'/':$0);},$7:function(){if(this.$5()){return this;}return new SystemEx.IO.FileInfo(this.$1,(this.$0==null)?SystemEx.IO.FileInfo.root:this.$0.$7());},$8:function(){return this.$9().$6();},$9:function(){var $0=((this.$0==null)?null:this.$0.$9());if(this.$1==='.'){return (($0==null)?SystemEx.IO.FileInfo.root:$0);}if(($0!=null)&&($0.$1==='')){$0=null;}if(this.$1==='..'){if($0==null){return SystemEx.IO.FileInfo.root;}if($0.$0==null){return SystemEx.IO.FileInfo.root;}return $0.$0;}return new SystemEx.IO.FileInfo(this.$1,(($0==null)&&(this.$1!==''))?SystemEx.IO.FileInfo.root:$0);},$A:function(){try{return (SystemEx.Html.LocalStorage.getItem(this.$8())!=null);}catch($0){if($0.message.startsWith('IOException')){return false;}throw $0;}},$B:function(){try{var $0=SystemEx.Html.LocalStorage.getItem(this.$8());return (($0!=null)&&!$0.startsWith('{'));}catch($1){if($1.message.startsWith('IOException')){return false;}throw $1;}},get_length:function(){try{if(!this.$A()){return 0;}var $0=new SystemEx.IO.FileStream(this,6,1);var $1=$0.get_length();$0.close();return $1;}catch($2){if($2.message.startsWith('IOException')){return 0;}throw $2;}},createNewFile:function(){if(this.$A()||!this.$0.$A()){return false;}SystemEx.Html.LocalStorage.setItem(this.$8(),window.btoa(''));return true;},$C:function(){try{if(!this.$A()){return false;}SystemEx.Html.LocalStorage.removeItem(this.$8());return true;}catch($0){if($0.message.startsWith('IOException')){return false;}throw $0;}},$D:function(){try{if((this.$0!=null)&&!this.$0.$A()){return false;}if(this.$A()){return false;}SystemEx.Html.LocalStorage.setItem(this.$8(),'{}');return true;}catch($0){if($0.message.startsWith('IOException')){return false;}throw $0;}},$E:function(){if(this.$0!=null){this.$0.$E();}return this.$D();},listFiles:function(predicate){var $0=[];try{var $1=this.$8();if(!$1.endsWith('/')){$1+='/';}var $2=$1.length;var $3=SystemEx.Html.LocalStorage.get_length();for(var $4=0;$4<$3;$4++){var $5=SystemEx.Html.LocalStorage.key($4);if($5.startsWith($1)&&($5.indexOf('/',$2)===-1)){var $6=$5.substring($2,$5.length);if((predicate==null)||predicate.invoke($6,this)){$0.add(new SystemEx.IO.FileInfo($6,this));}}}}catch($7){}return $0;}}
SystemEx.IO.FileStream=function(fileInfo,fileMode,fileAccess){SystemEx.IO.FileStream.initializeBase(this);this.$0=fileInfo.$8();if((fileAccess!==1)&&(fileAccess!==3)){throw new Error('IllegalArgumentException: fileAccess');}this.$1=(fileAccess===3);if(fileInfo.$A()){try{this.$3=window.atob(SystemEx.Html.LocalStorage.getItem(this.$0));this.$7=this.$3.length;}catch($0){throw (($0.message.startsWith('IOException'))?new Error('FileNotFoundException:'+$0):$0);}}else if(this.$1){this.$3='';this.$2=true;try{this.$9();}catch($1){throw (($1.message.startsWith('IOException'))?new Error('FileNotFoundException:'+$1):$1);}}else{throw new Error('FileNotFoundException:'+this.$0);}}
SystemEx.IO.FileStream.prototype={$0:null,$1:false,$2:false,$3:null,$4:0,$5:null,$6:0,$7:0,get_filePointer:function(){return this.$6;},seek:function(position){if(position<0){throw new Error('IllegalArgumentException:');}this.$6=position;},get_length:function(){return this.$7;},set_length:function(value){if(this.$7!==value){this.$8();if(this.$3.length>value){this.$3=this.$3.substring(0,value);this.$7=value;}else{while(this.$7<value){this.writeByte(0);}}}return value;},get_poition:function(){return this.$6;},close:function(){if(this.$3!=null){this.$9();this.$3=null;}},$8:function(){if(this.$5==null){return;}if(this.$3.length<this.$4){var $1=new ss.StringBuilder();while(this.$3.length+SystemEx.StringBuilderEx.getLength($1)<this.$4){$1.append('\u0000');}this.$3+=$1.toString();}var $0=this.$4+SystemEx.StringBuilderEx.getLength(this.$5);this.$3=this.$3.substring(0,this.$4)+this.$5.toString()+(($0<this.$3.length)?this.$3.substring($0,this.$3.length):'');this.$5=null;},$9:function(){if(!this.$2){return;}this.$8();SystemEx.Html.LocalStorage.setItem(this.$0,window.btoa(this.$3));this.$2=false;},readByte:function(){if(this.$6>=this.$7){return -1;}else{this.$8();return this.$3.charAt(this.$6++);}},writeByte:function(b){if(!this.$1){throw new Error('IOException: not writeable');}if(this.$5==null){this.$4=this.$6;this.$5=new ss.StringBuilder();}else if(this.$4+SystemEx.StringBuilderEx.getLength(this.$5)!==this.$6){this.$8();this.$4=this.$6;this.$5=new ss.StringBuilder();}this.$5.append((b&255));this.$6++;this.$7=Math.max(this.$6,this.$7);this.$2=true;}}
SystemEx.IO.Path=function(){}
SystemEx.IO.Directory=function(){}
SystemEx.IO.Directory.exists=function(path){if(path==null){throw new Error('ArgumentNullException: path');}return new SystemEx.IO.FileInfo(path).$A();}
SystemEx.IO.File=function(){}
SystemEx.IO.File.delete_=function(path){if(path==null){throw new Error('ArgumentNullException: path');}return new SystemEx.IO.FileInfo(path).$C();}
SystemEx.IO.File.exists=function(path){if(path==null){throw new Error('ArgumentNullException: path');}return new SystemEx.IO.FileInfo(path).$A();}
SystemEx.IO.Stream=function(){}
SystemEx.IO.Stream.prototype={read:function(b,offset,length){if((offset===0)&&(length===0)){length=b.length;}var $0=offset+length;for(var $1=offset;$1<$0;$1++){var $2=this.readByte();if($2===-1){return (($1===offset)?-1:$1-offset);}b[$1]=$2;}return length;},write:function(b,offset,length){if((offset===0)&&(length===0)){length=b.length;}var $0=offset+length;for(var $1=offset;$1<$0;$1++){this.writeByte(b[$1]);}}}
SystemEx.Html.CloseEventArgs.registerClass('SystemEx.Html.CloseEventArgs');SystemEx.Html.MessageEventArgs.registerClass('SystemEx.Html.MessageEventArgs');SystemEx.Html.WebSocket.registerClass('SystemEx.Html.WebSocket');SystemEx.Html.LocalStorage.registerClass('SystemEx.Html.LocalStorage');SystemEx.JSArrayEx.registerClass('SystemEx.JSArrayEx');SystemEx.JSConvertEx.registerClass('SystemEx.JSConvertEx');SystemEx.StringBuilderEx.registerClass('SystemEx.StringBuilderEx');SystemEx.IO.Stream.registerClass('SystemEx.IO.Stream');SystemEx.IO.MemoryStream.registerClass('SystemEx.IO.MemoryStream',SystemEx.IO.Stream);SystemEx.IO.SE.registerClass('SystemEx.IO.SE');SystemEx.IO.FileInfo.registerClass('SystemEx.IO.FileInfo');SystemEx.IO.FileStream.registerClass('SystemEx.IO.FileStream',SystemEx.IO.Stream);SystemEx.IO.Path.registerClass('SystemEx.IO.Path');SystemEx.IO.Directory.registerClass('SystemEx.IO.Directory');SystemEx.IO.File.registerClass('SystemEx.IO.File');SystemEx.Html.WebSocket.CONNECTING=0;SystemEx.Html.WebSocket.OPEN=1;SystemEx.Html.WebSocket.CLOSING=2;SystemEx.Html.WebSocket.CLOSED=3;SystemEx.JSConvertEx.$0=new Int8Array(4);SystemEx.JSConvertEx.$1=new Int32Array(SystemEx.JSConvertEx.$0.buffer,0,1);SystemEx.JSConvertEx.$2=new Float32Array(SystemEx.JSConvertEx.$0.buffer,0,1);(function(){ss.StringBuilder.prototype.baseAppend = ss.StringBuilder.prototype.append;
    ss.StringBuilder.prototype.baseClear = ss.StringBuilder.prototype.clear;
    ss.StringBuilder.prototype.append = function(s) { if (!ss.isNullOrUndefined(s)) this.length += s.length; return this.baseAppend(s); }
    ss.StringBuilder.prototype.clear = function(s) { this.length = 0; return this.baseClear(); }
    ss.StringBuilder.prototype.length = 0;})();
SystemEx.IO.FileInfo.separatorChar='/';SystemEx.IO.FileInfo.separator='/';SystemEx.IO.FileInfo.root=new SystemEx.IO.FileInfo('');}
ss.loader.registerScript('Script.WebEx',[],executeScript);})();// This script was generated using Script# v0.6.1.0
