//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.CoreEx_ {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Local {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Local() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.CoreEx_.Local", typeof(Local).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel must be the channel head..
        /// </summary>
        internal static string ChannelHeadRequired {
            get {
                return ResourceManager.GetString("ChannelHeadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; already exists..
        /// </summary>
        internal static string DirectoryAExist {
            get {
                return ResourceManager.GetString("DirectoryAExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate key..
        /// </summary>
        internal static string DuplicateKey {
            get {
                return ResourceManager.GetString("DuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExceedRecurseCount.
        /// </summary>
        internal static string ExceedRecurseCount {
            get {
                return ResourceManager.GetString("ExceedRecurseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hash cannot be modified during enumeration..
        /// </summary>
        internal static string HashChangeNotAllowedDuringEnumeration {
            get {
                return ResourceManager.GetString("HashChangeNotAllowedDuringEnumeration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index must be between &apos;{0}&apos; and &apos;{1}&apos;..
        /// </summary>
        internal static string IndexOutOfRangeAB {
            get {
                return ResourceManager.GetString("IndexOutOfRangeAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid array length..
        /// </summary>
        internal static string InvalidArrayLength {
            get {
                return ResourceManager.GetString("InvalidArrayLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidArrayNullItem.
        /// </summary>
        internal static string InvalidArrayNullItem {
            get {
                return ResourceManager.GetString("InvalidArrayNullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cryptography public key..
        /// </summary>
        internal static string InvalidCryptPublicKey {
            get {
                return ResourceManager.GetString("InvalidCryptPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidDataSource.
        /// </summary>
        internal static string InvalidDataSource {
            get {
                return ResourceManager.GetString("InvalidDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string InvalidIdA {
            get {
                return ResourceManager.GetString("InvalidIdA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidUri.
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length provided to PrimaryKey does not match array length of defined Primary Key..
        /// </summary>
        internal static string MismatchPrimaryKey {
            get {
                return ResourceManager.GetString("MismatchPrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array length provided to RowVersion does not match array length of defined RowVersion..
        /// </summary>
        internal static string MismatchRowVersion {
            get {
                return ResourceManager.GetString("MismatchRowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is before first the entry or after the last entry..
        /// </summary>
        internal static string PositionOutOfBound {
            get {
                return ResourceManager.GetString("PositionOutOfBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineCacheDependency.
        /// </summary>
        internal static string RedefineCacheDependency {
            get {
                return ResourceManager.GetString("RedefineCacheDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineCalculatedValue.
        /// </summary>
        internal static string RedefineCalculatedValue {
            get {
                return ResourceManager.GetString("RedefineCalculatedValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel &apos;{0}&apos; already defined..
        /// </summary>
        internal static string RedefineChannelA {
            get {
                return ResourceManager.GetString("RedefineChannelA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineDataSource.
        /// </summary>
        internal static string RedefineDataSource {
            get {
                return ResourceManager.GetString("RedefineDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RedefineDataSourceCache [{0}], &apos;{1}&apos;.
        /// </summary>
        internal static string RedefineDataSourceCacheAB {
            get {
                return ResourceManager.GetString("RedefineDataSourceCacheAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to redefine Primary Key..
        /// </summary>
        internal static string RedefinePrimaryKey {
            get {
                return ResourceManager.GetString("RedefinePrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to redefine RowVersion..
        /// </summary>
        internal static string RedefineRowVersion {
            get {
                return ResourceManager.GetString("RedefineRowVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to redefine font &apos;{0}&apos;..
        /// </summary>
        internal static string RedefineRtfFontA {
            get {
                return ResourceManager.GetString("RedefineRtfFontA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to redefine table column..
        /// </summary>
        internal static string RedefineTableColumn {
            get {
                return ResourceManager.GetString("RedefineTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree &apos;{0}&apos; already defined..
        /// </summary>
        internal static string RedefineTreeA {
            get {
                return ResourceManager.GetString("RedefineTreeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &apos;{0}&apos; cannot contain scope characters..
        /// </summary>
        internal static string ScopeCharacterNotAllowedA {
            get {
                return ResourceManager.GetString("ScopeCharacterNotAllowedA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source directory &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string SourceDirectoryANotExist {
            get {
                return ResourceManager.GetString("SourceDirectoryANotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree must be the tree head..
        /// </summary>
        internal static string TreeHeadRequired {
            get {
                return ResourceManager.GetString("TreeHeadRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a SmartForm type..
        /// </summary>
        internal static string TypeNotSmartForm {
            get {
                return ResourceManager.GetString("TypeNotSmartForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create object &apos;{0}&apos;..
        /// </summary>
        internal static string UnableCreateObjectA {
            get {
                return ResourceManager.GetString("UnableCreateObjectA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create singleton &apos;{0}&apos;..
        /// </summary>
        internal static string UnableCreateSingletonA {
            get {
                return ResourceManager.GetString("UnableCreateSingletonA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unable to locate class &apos;{0}&apos;..
        /// </summary>
        internal static string UnableGetTypeA {
            get {
                return ResourceManager.GetString("UnableGetTypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined_.
        /// </summary>
        internal static string Undefined_ {
            get {
                return ResourceManager.GetString("Undefined_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedApplicationUnit &apos;{0}&apos;..
        /// </summary>
        internal static string UndefinedApplicationUnitA {
            get {
                return ResourceManager.GetString("UndefinedApplicationUnitA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined CommandId..
        /// </summary>
        internal static string UndefinedCommandId {
            get {
                return ResourceManager.GetString("UndefinedCommandId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined configuration section..
        /// </summary>
        internal static string UndefinedConfigurationSection {
            get {
                return ResourceManager.GetString("UndefinedConfigurationSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid config path &apos;{0}&apos;..
        /// </summary>
        internal static string UndefinedCryptPathA {
            get {
                return ResourceManager.GetString("UndefinedCryptPathA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing appSetting key &apos;{1}&apos; or bad value..
        /// </summary>
        internal static string UndefinedCryptPathConfigAB {
            get {
                return ResourceManager.GetString("UndefinedCryptPathConfigAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing registry key &apos;{1}&apos; or bad value..
        /// </summary>
        internal static string UndefinedCryptPathRegistryAB {
            get {
                return ResourceManager.GetString("UndefinedCryptPathRegistryAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing appSetting key &apos;{1}\\SystemCryptKey&apos; or bad value in &apos;{0}&apos;..
        /// </summary>
        internal static string UndefinedCryptPathValueAB {
            get {
                return ResourceManager.GetString("UndefinedCryptPathValueAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public key is not defined..
        /// </summary>
        internal static string UndefinedCryptPublicKey {
            get {
                return ResourceManager.GetString("UndefinedCryptPublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture &apos;{0}&apos; undefined..
        /// </summary>
        internal static string UndefinedCultureA {
            get {
                return ResourceManager.GetString("UndefinedCultureA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedDataSourceRegistration [{0}].
        /// </summary>
        internal static string UndefinedDataSourceRegistrationA {
            get {
                return ResourceManager.GetString("UndefinedDataSourceRegistrationA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedDataSourceRegistration [{0}], &apos;{1}&apos;.
        /// </summary>
        internal static string UndefinedDataSourceRegistrationAB {
            get {
                return ResourceManager.GetString("UndefinedDataSourceRegistrationAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested item &apos;{0}&apos; not defined..
        /// </summary>
        internal static string UndefinedKeyA {
            get {
                return ResourceManager.GetString("UndefinedKeyA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined font &apos;{0}&apos;..
        /// </summary>
        internal static string UndefinedRtfFontA {
            get {
                return ResourceManager.GetString("UndefinedRtfFontA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined table base update..
        /// </summary>
        internal static string UndefinedTableBaseUpdate {
            get {
                return ResourceManager.GetString("UndefinedTableBaseUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined table schema..
        /// </summary>
        internal static string UndefinedTableSchema {
            get {
                return ResourceManager.GetString("UndefinedTableSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedTransactionContext.
        /// </summary>
        internal static string UndefinedTransactionContext {
            get {
                return ResourceManager.GetString("UndefinedTransactionContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined type..
        /// </summary>
        internal static string UndefinedType {
            get {
                return ResourceManager.GetString("UndefinedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UndefinedValueReplacer.
        /// </summary>
        internal static string UndefinedValueReplacer {
            get {
                return ResourceManager.GetString("UndefinedValueReplacer", resourceCulture);
            }
        }
    }
}
